runtime: python39  # Use the Python 3.9 runtime (adjust as needed for your app)

env: standard  # Standard environment (other option: flexible)

entrypoint: gunicorn -b :$PORT main:app  # Adjust the command to start your app

instance_class: F2  # Specify the instance class (optional)

env_variables:
  VAR_NAME: "value"  # You can define environment variables here

automatic_scaling:
  min_instances: 1  # Minimum number of instances
  max_instances: 10  # Maximum number of instances
  target_cpu_utilization: 0.65  # CPU utilization threshold for scaling

handlers:
  - url: /static
    static_dir: static  # Serve static files from the 'static' directory

  - url: /.*
    script: auto  # Route all other requests to your app
